sudo: required
services:
    - docker

before_install:
    - docker build -t surajsingla333/docker-react -f Dockerfile.dev .

script:
    - docker run surajsingla333/docker-react npm run test -- --coverage

deploy:
    provider: heroku
    api_key:
        secure: YLa1GtjNDFUMivQIqQmahlwfTfkc+Ltt1xAzpi7+Wtjy+j5+3UazC66L94gzRWVYLz2wXi7cqOLuzZ8wJuRtxrE0E6/GgUPHAynU5SEHhHHK2W4RkBrjaPPHaMiPo67Mp4ZQVQgZF7Audu/60JhREXC8hhw1xC+NlgJmXSmE933BHAhZ2xDkJKXuwt7aFdUugA5Zu2yQWiG+hfro7Nn3HBPOah30qw2zlYs6dRflOakJVUxa2EAGGtgt7xSyfttEIudxW1Ck0ZBXdzwAKseDh6j26PeFup6dzpWgglASaP7He5CoD/1wMKPrB2EttlhT9Rg3kLtYgudr2bKJScJJDg75+ikO5oijCO0ignBDd/bVPkLZd6popRQaDEqgDKDC8yC4Qb9BqS9fyxHrnDbWWMT2Np5dQdZj4eKenVgmgPQ9peQBege3g7f0EI7ljdcyUyfsqmbIDgui/QU25HH/1Y1ucZR1ovMGoyfcoMnEG2Xx+QfN/rDn/FWqwS67L30LLjcU9An7y4k0M0zw0I8buRQcAxCvNG2/C3OFnu+Pl9m8R4CFYwynWFXHzRD0S3M2oW40XZtJMdpQnnD15GJ4MCdLchwTffBCVSFaGh/1QPseZeuHRZheT7arfLFyudtThzh6JXd8/CtgGEBsdkg26l/bVrSag60JbTWh6tL6wEA=
    app: dockerreact
    on:
        repo: surajsingla333/reactDocker

# AWS as in tutorial
# deploy:
#     provider: elasticbeanstalk
#     region: "us-west-2" # region where we created
#     app: "dockerReact" # name of the app on elastic
#     env: "Docker-env" # docker environment
#     bucket_name: "elasticbeanstalk" #zip file to be called on elastic
#     bucket_path: "dockerReact" # same as app
#     on:
#         branch: master

    
    
