sudo: required
services:
    - docker

before_install:
    - docker build -t surajsingla333/docker-react -f Dockerfile.dev .

script:
    - docker run surajsingla333/docker-react npm run test -- --coverage