sudo: required
services:
    - docker

before_install:
    - docker build -t surajsingla333/docker-react -f Dockerfile.dev .

script:
    - docker run surajsingla333/docker-react npm run test -- --coverage

deploy:
    provider: heroku
    api_key:
        secure: d86fcc6a-ac1c-4d48-a62b-35c6934acfd4
    app: dockerreact
    on:
        repo: surajsingla333/reactDocker
        branch: master

# AWS as in tutorial
# deploy:
#     provider: elasticbeanstalk
#     region: "us-west-2" # region where we created
#     app: "dockerReact" # name of the app on elastic
#     env: "Docker-env" # docker environment
#     bucket_name: "elasticbeanstalk" #zip file to be called on elastic
#     bucket_path: "dockerReact" # same as app
#     on:
#         branch: master

    
    
