sudo: required
services:
    - docker

before_install:
    - docker build -t surajsingla333/dockerReact -f Dockerfile.dev .

script:
    - docker run surajsingla333/dockerReact npm run test -- --coverage