version: '3'
services:
    reactdocker:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3001:3000"
        volumes:
            - /home/app/node_modules
            - .:/home/app
    tests: 
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /home/app/node_modules
            - .:/home/app
        command: ['npm', 'test']